### PR TITLE
Some fixes and improvements

### PR DESCRIPTION
**Pull request by guyeeba**
- development environment: Kodi 15.2 on OSMC, Win 10 Mobile 10586.36

- gave files view a clearer user interface
- fixed occasional crash on rpc requests (NullReferenceException in HttpClient.SendAsync, I have no idea what exactly caused it, but reducing the number of simultaneous HttpClients fixed the issue)
- fixed numerous crashes on missing fields in RPC responses (happened mostly when Kodi was playing video from file, not from library, so no metadata was received from Kodi)
- reorganized RPC request handling, now it supports (and uses automatically) batch requests. HttpClient concurrency can be limited. Interface-compatible with original implementation.
- replaced arrow buttons on remote control with RepeatButton, because... dunno, I always prefer built-in implementations, they're... clearer, and more future-proof :D
- subtitle button on remote control now lets you select the desired subtitle, you don't have to step through them (does not seem to work, even though I do everything according to the specification... or maybe I missed something? NE1 with ideas, please help)
- I used the same selection method in the newly-added audiostream button
- removed unnecessary usings
- completed Hungarian translations

- not tested thoroughly... well... not at all :)

If anyone interested, please test on WP8.1 devices, and design better looking SourceFilesPage templates, as I suck at UI design

### CODE REVIEW

**Comment by akshay2000** [comment]
This is a great list of features. I will have to test it before I merge it to master.  
On a side note: While you have summarized the feature list nicely, you seem to have put everything into single commit. This is generally considered a bad practice. Please try to [commit early, commit often](http://www.databasically.com/2011/03/14/git-commit-early-commit-often/). Just a suggestion. Keep up the good work.

**Comment by guyeeba** [comment]
Yeah, sorry, usually I try to follow the "commit early, commit often" policy, but my original intention was just to fix the NullReferenceException, and then to send the changes to you by email, no fork needed... well, I had some free time in the past few days, so it became a much bigger commit. :)

**Comment by akshay2000** [comment]
This won't compile (my best guess, anyway) since newly added files haven't been checked in.

**Comment by guyeeba** [comment]
Ehhh, dammit... it's my first time I used Visual Studio with github, but I have no idea why it skipped the new files... unfortunately I'm not at home right now, but I'll commit them as soon as I get home.

**Comment by guyeeba** [comment]
Are there any more missing files?

**Comment by akshay2000** [comment]
I don't understand the purpose of `BoolToVisibilityConverter2`. Wasn't existing converter sufficient? It seems to be doing the same job.

**Comment by guyeeba** [comment]
`BoolToVisibilityConverter2`: I created it because I wanted to leave a chance to handle the null value of `bool?`. I don't know how the standard converter behaves with null values, so if they're equivalent, then (as in its current implementation it doesn't make sense to differentiate null values), it's pointless, I agree...

`ExecuteRpcRequest`: the function itself is synchronous, because it does nothing asynchronously, it just puts the request in a "queue", and returns the `Task` of a corresponding `TaskCompletionSource`. You still can await for the `Task` it returns, because you wait for the `TaskCompletionSource` to finish, not for the function itself, and that's the intended behavior. One might say that the event handler is async, but we don't event wait for the handler to complete. All we want to wait for is the request's `TaskCompletionSource.Task` in the caller of `ExecuteRpcRequest`, and this implementation is just fine for that purpose.

But correct me if I'm wrong. :)

**Pull request merged**
