### PR TITLE
Fix unresponsive Cortana search results list

### PR DESCRIPTION
**Pull request by christianprescott**
Issue #25

### CODE REVIEW

**Comment by akshay2000** [comment]
This handler also handles when the list contains only one item. When only one search result is found, the item starts playing automatically. Tapping it would result in stopping and restarting the playback from the beginning. Could you add a check to ensure that the list indeed contains more than one item?

**Comment by christianprescott** [comment]
Didn't realize it worked that way. Will add logic for that.

**Comment by christianprescott** [comment]
Take another look at c5824244735cc017dcc26fb477c7c16fc7e79b3e. diff didn't like my braces I guess... but the block has been wrapped with a searchHitState condition.

**Comment by christianprescott** [comment]
One last change: tapping the single item from from a search with one result will continue without restarting the auto-played media. Same as clicking "Yes" button. A better experience IMO.

**Comment by akshay2000** [comment]
Do you mean that tapping the single item should navigate to the CoverPage, just like tapping yes?  
That does sound good!

**Comment by christianprescott** [comment]
Precisely! A little less friction for user to confirm "Yes, that one."

**Comment by akshay2000** [comment]
Well, go ahead if you want to make it happen.

**Comment by christianprescott** [comment]
Should clarify: change was made in eb865a7eeb4b4f310c02fbe63f9a17f53e2f098f. I am satisfied that the issue is resolved.

**Comment by akshay2000** [comment]
If you have finished working with this request, I shall merge it. Sounds good?

**Comment by christianprescott** [comment]
Sounds good

**Pull request merged**
