### PR TITLE
fixed old folders bug

### PR DESCRIPTION
**Pull request by gabrielsadaka**
I was thinking instead of playing the file automatically when pressed we can include a play icon on the left and if they tap on that it will play it and if they tap on the text it will navigate to the page relevant to it. What do you think?

### CODE REVIEW

**Comment by akshay2000** [comment]
I'm really not sure what 'page relevant to it' could be. And anyhow, that seems to complicate things (for users as well as us) unnecessarily. We will consider that if users request it. For now, this is good! Thanks for fixing the bug.
I've merged changes from @christianprescott on RT side. Check those out! Let's get that published.

**Comment by gabrielsadaka** [comment]
I meant if its a movie it should go to the movie's page for example however I agree with you, will leave it for now. I'll have a look at the changes soon and see if I have anything else to add otherwise we can finally make it live!

**Comment by gabrielsadaka** [comment]
Just had a look at all of the changes in the dev branch, it looks good but there is still quite a bit of cleaning up to do so it may take a few weeks to get it done.

**Comment by akshay2000** [comment]
Yup. UI does need to be cleaned up. We'll work it out though. All I am aiming for is presentable. It doesn't have to be beautiful, per se. Presentable is good enough!

**Comment by akshay2000** [comment]
Yup. UI does need to be cleaned up. We'll work it out though. All I am aiming for is presentable. It doesn't have to be beautiful, per se. Presentable is good enough!

**Pull request merged**
