### PR TITLE
Fix for exception with MusicBrainz tokens:

### PR DESCRIPTION
**Pull request by vinser**
Newtonsoft.Json.JsonReaderException was unhandled by user code
  HResult=-2146233088
  LineNumber=1
  LinePosition=265
  Message=Error reading string. Unexpected token: StartArray. Path '[0].musicbrainzalbumartistid', line 1, position 265.
  Path=[0].musicbrainzalbumartistid
  Source=Newtonsoft.Json
  StackTrace:
       at Newtonsoft.Json.JsonReader.ReadAsStringInternal()
       at Newtonsoft.Json.Linq.JTokenReader.ReadAsString()
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
       at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
       at Newtonsoft.Json.Linq.JToken.ToObject[T]()
       at XBMCRemoteRT.RPCWrappers.AudioLibrary.<GetRecentlyAddedAlbums>d__1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at XBMCRemoteRT.CoverPage.<RefreshListsIfNull>d__15.MoveNext()
  InnerException:

### CODE REVIEW

**Comment by vinser** [comment]
The app startup threw unhendled exception when getting music library content with unexepted json token. I have to delimit some with underscore as they do in kodi tests and now it works fine. Tested on local machine and on wp emulator.

**Comment by akshay2000** [comment]
Looks like serialization naming issue. I have a few thoughts about this:

1. Does this break compatibility with the current versions? That is version 14 to 16. I have a strong feeling that this will cause issue.
2. As far as the app is concerned, those properties are completely ignored and seem safe to remove. I think we would benefit from removal. This addresses point 1.
3. C# conventions follow pascal case, not underscores. So, if we indeed decide to keep the properties, I strongly recommend keeping them in pascal case and using `JsonProperty` attribute to address naming.

I am personally in favor of removing the properties since it doesn't break the compatibility. Please test accordingly and push commits. They will be added to this pull request automatically.

**Comment by vinser** [comment]
Since I have not found references to attributes MUZ in application, the first thing I decided to simply remove/comment them and all works fine. But later I  renamed then in case they are needed. 
Should I new pull or you do it yourself?

**Comment by vinser** [comment]
Will you be so kind as to post it in Store, tnx

**Comment by akshay2000** [comment]
The app has already been queued for the update. Usual turnover time for approval was 24 hours. It might have changed in the mean time. You should be able to see the app updated in about a week. The update also includes some bug fixes and improvements in the file browser. However, this is as much as I can do right now. It's gonna take its own time to go through the Store approval process.

**Pull request merged**
