### PR TITLE
Added 'now playing' page which lists the currently playing songs

### PR DESCRIPTION
**Pull request by eraser85**
- Added the NowPlaying page which lists (for now) the currently playing audio tracks.
- To allow the NowPlaying page to display which item is the one currently playing I've added a ItemId in the PlayerState global class.
- Player RPCWrapper can now play the n-th element in a list (not just prev, next).
- Kodi Assist supports now server addresses starting with http:// (in case a user configured his kodi to be accessible from outside thanks to the various free dyndns services).
- Https protocol is not supported and a message pops up if the user tries to setup such an address.

### CODE REVIEW

**Comment by akshay2000** [comment]
1. Why was http:// address support explicitly needed? Simply entering the hostname (on in this case) should have sufficed since internally http:// is anyway added to the URI. What am I missing?  
2. I don't see any obvious way to access now playing through UI? Is it on purpose (to let me decide how to access it)? Or did I miss it?  
3. Why are the converters inheriting from `FrameworkElement`. I'm not exactly sure about the purpose of those classes yet since I couldn't actually see the page, but something feels wrong about having a `FrameworkElement` in namespace called `Converters`.

**Comment by eraser85** [comment]
1. http:// is useful when you do copy paste (copying from onenote where I have my list of addresses or email when I activate the dyndns thing). Anyway it wasn't throwing errors when typing http://, simply the connection wasn't working. Now it does. And if you type https it says that it's not supported. Not game changing but at least you now don't make assumptions.

2. Maybe you missed the "list" button next to "next" in the coverpage ;)

3. If you looked closer the converters have FrameworkElement because they expose a dependency property. It's the only way to have some kind of multi-binding in WinRT. In this way I'm able to bind both SongId (from song class) and ItemId in PlayerState to each song in the now playing list.

**Comment by akshay2000** [comment]
1. That's a nice usability consideration. Thanks.
2. Yup. I totally missed that button. No idea why though. I discovered it later on.
3. Interesting workaround. You could bind the highlighting directly to SongId and then converter could check against the current id in global state. But then UI won't update when the global state changes. So yeah, I guess this is the way to go.
4. Just for future reference, try to keep commits smaller. [Commit early, commit often](http://blog.codinghorror.com/check-in-early-check-in-often/).

**Comment by eraser85** [comment]
Sorry for not following that policy. This was my first ever contribution to an open source project and I still need to understand how things work. Happy to know my contribution was accepted 😊

**Comment by akshay2000** [comment]
@eraser85 No problem. I thought it would be helpful for new users if they had guidelines to follow. So I wrote a [blog post](http://blog.indestructible.in/tips-on-contributing-to-projects/).

**Pull request merged**
